import { mkdirSync, readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  buildVitestBaseOutput,
  computeVitestMetrics,
  runVitestCoverage,
} from "./metrics/vitestMetrics.js";
import { exportVitestBundle } from "./platform/exportVitestBundle.js";
import { verifyVitestJson } from "./verify/verifyVitestJson.js";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUTPUT = join(ROOT, "vitest.json");

export async function runVitestTrigger(skipVerify = false): Promise<number> {
  console.log("Starting Vitest platform trigger (Error Flow Verification)");
  mkdirSync(join(ROOT, "artifacts", "training"), { recursive: true });

  const coverage = runVitestCoverage(ROOT);
  if (!coverage) {
    console.error("FAIL: coverage-summary.json was not generated by Vitest");
    return 1;
  }

  const metrics = computeVitestMetrics(coverage);
  const base = buildVitestBaseOutput(metrics, coverage);
  exportVitestBundle(ROOT, base, metrics);
  console.log(`Wrote ${OUTPUT}`);

  if (!skipVerify) {
    const data = JSON.parse(readFileSync(OUTPUT, "utf-8")) as Record<string, unknown>;
    const code = verifyVitestJson(OUTPUT, data);
    if (code !== 0) return code;
  }

  const final = JSON.parse(readFileSync(OUTPUT, "utf-8")) as {
    metrics: Array<{ score: number; covered: string }>;
  };
  const ok = final.metrics.every((m) => m.score === 100 && m.covered === "yes");
  console.log(
    `\nTRIGGER COMPLETE: vitest.json — Error Flow Verification 100/100=${ok}`,
  );
  return ok ? 0 : 1;
}

const skip = process.argv.includes("--skip-verify");
runVitestTrigger(skip).then((code) => process.exit(code));
